
set(iotexplorer_base 3rdparty/tencentcloud-sdk-cpp/iotexplorer)
set(core_base 3rdparty/tencentcloud-sdk-cpp/core)


configure_file(${core_base}/src/Config.h.in ${core_base}/include/tencentcloud/core/Config.h @ONLY)

set(core_public_header
    ${core_base}/include/tencentcloud/core/AbstractClient.h
    ${core_base}/include/tencentcloud/core/AbstractModel.h
    ${core_base}/include/tencentcloud/core/AsyncCallerContext.h
    ${core_base}/include/tencentcloud/core/CommonClient.h
    ${core_base}/include/tencentcloud/core/Config.h
    ${core_base}/include/tencentcloud/core/Credential.h
    ${core_base}/include/tencentcloud/core/Error.h
    ${core_base}/include/tencentcloud/core/Executor.h
    ${core_base}/include/tencentcloud/core/NetworkProxy.h
    ${core_base}/include/tencentcloud/core/Outcome.h
    ${core_base}/include/tencentcloud/core/Runnable.h
    ${core_base}/include/tencentcloud/core/Sign.h
    ${core_base}/include/tencentcloud/core/TencentCloud.h
    )

set(core_public_header_http
    ${core_base}/include/tencentcloud/core/http/Http.h
    ${core_base}/include/tencentcloud/core/http/HttpClient.h
    ${core_base}/include/tencentcloud/core/http/HttpRequest.h
    ${core_base}/include/tencentcloud/core/http/HttpResponse.h
    ${core_base}/include/tencentcloud/core/http/Url.h
    )

set(core_public_header_profile
    ${core_base}/include/tencentcloud/core/profile/ClientProfile.h
    ${core_base}/include/tencentcloud/core/profile/HttpProfile.h
    )

set(core_public_header_utils
    ${core_base}/include/tencentcloud/core/utils/Utils.h
    )

set(core_public_header_utils_rapidjson
    ${core_base}/include/tencentcloud/core/utils/rapidjson
    )

set(core_src
    ${core_base}/src/AbstractClient.cpp
    ${core_base}/src/AbstractModel.cpp
    ${core_base}/src/AsyncCallerContext.cpp
    ${core_base}/src/CommonClient.cpp
    ${core_base}/src/Credential.cpp
    ${core_base}/src/Executor.cpp
    ${core_base}/src/NetworkProxy.cpp
    ${core_base}/src/Sign.cpp
    ${core_base}/src/TencentCloud.cpp
    ${core_base}/src/http/Http.cpp
    ${core_base}/src/http/HttpClient.cpp
    ${core_base}/src/http/HttpRequest.cpp
    ${core_base}/src/http/HttpResponse.cpp
    ${core_base}/src/http/Url.cpp
    ${core_base}/src/profile/ClientProfile.cpp
    ${core_base}/src/profile/HttpProfile.cpp
    ${core_base}/src/utils/Utils.cpp
)

include_directories(${core_base}/"include/tencentcloud/core/utils/rapidjson")

find_package(CURL REQUIRED)
find_package(OpenSSL REQUIRED)


add_library(tencentcore STATIC
    ${core_public_header}
    ${core_public_header_http}
    ${core_public_header_profile}
    ${core_public_header_utils}
    ${core_src})

target_include_directories(tencentcore
    PUBLIC ${core_base}/include)

target_link_libraries(tencentcore
    PUBLIC
    uuid
    ${OPENSSL_LIBRARIES}
    ${CURL_LIBRARIES} )

include_directories(${CURL_INCLUDE_DIR})
include_directories(${OPENSSL_INCLUDE_DIR})


set(iotexplorer_public_header
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/IotexplorerClient.h
)

set(iotexplorer_public_header_model
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UpdateDevicesEnableStateResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteProjectRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DevicesItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteFenceBindRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeModelDefinitionResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UnbindDevicesRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteDevicesResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyStudioProductResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetGatewaySubDeviceListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteStudioProductResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BindDevicesRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeGatewaySubProductsResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetDeviceListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/TopicRulePayload.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteLoRaFrequencyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeTopicPolicyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BindProductInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyPositionFenceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PositionFenceItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PositionItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyModelDefinitionRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateStudioProductResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CallDeviceActionSyncRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ProductDevicesPositionItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDevicePositionListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetDeviceLocationHistoryResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UpdateFirmwareResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyPositionFenceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyStudioProductRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyPositionSpaceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateStudioProductRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ProductModelDefinition.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyFenceBindResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateBatchProductionRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeletePositionFenceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/FenceAlarmPoint.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UploadFirmwareRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ListEventHistoryRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceDataRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/FenceBindProductItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PublishRRPCMessageRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DevicePositionItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ListTopicPolicyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchPositionSpaceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribePositionFenceListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GenSingleDeviceSignatureOfPublicResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDevicePositionListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetProjectListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateProjectRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeProjectResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UnbindProductsRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchStudioProductResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeviceData.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetTopicRuleListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/FenceBindDeviceItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeviceDataHistoryItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetFamilyDeviceUserListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BindDeviceInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ProjectEntryEx.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeBatchProductionResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ListTopicPolicyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeLoRaFrequencyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteDeviceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteLoRaFrequencyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ControlDeviceDataRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ListFirmwaresResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ReleaseStudioProductResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeSpaceFenceEventListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PositionFenceInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteLoRaGatewayRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UnbindProductsResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeTopicPolicyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchPositionSpaceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/LoRaFrequencyEntry.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyTopicPolicyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetPositionSpaceListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeFenceEventListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UpdateDevicesEnableStateRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetDeviceLocationHistoryRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CallDeviceActionSyncResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateLoRaGatewayRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ReleaseStudioProductRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateProjectResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceDataHistoryResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteProjectResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateTopicPolicyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateDeviceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateDeviceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeletePositionSpaceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetStudioProductListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeFirmwareTaskResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/FirmwareInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DisableTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/TopicRuleInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetCOSURLRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeStudioProductResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateFenceBindRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ListFirmwaresRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetStudioProductListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PublishMessageRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/FamilySubDevice.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetDeviceListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifySpacePropertyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetPositionSpaceListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetCOSURLResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyFenceBindRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetTopicRuleListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeFenceEventListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyPositionSpaceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetLoRaGatewayListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ProjectEntry.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyLoRaGatewayResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/EventHistoryItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DirectBindDeviceInFamilyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/TopicRule.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CallDeviceActionAsyncRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CallDeviceActionAsyncResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteFenceBindResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteTopicPolicyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateFenceBindResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreatePositionFenceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/TopicItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeFenceBindListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeBindedProductsResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeviceSignatureInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PositionSpaceInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/LoRaGatewayLocation.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribePositionFenceListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeBatchProductionRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateTopicPolicyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DirectBindDeviceInFamilyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetFamilyDeviceUserListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeBindedProductsRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeLoRaFrequencyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ProductEntry.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeGatewaySubDeviceListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeSpaceFenceEventListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetLoRaGatewayListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/FenceEventItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeProjectRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UnbindDevicesResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyLoRaFrequencyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UploadFirmwareResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyTopicPolicyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateLoRaGatewayResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteTopicPolicyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteLoRaGatewayResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateLoRaFrequencyRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/LoRaGatewayItem.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceBindGatewayResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeGatewaySubDeviceListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ControlDeviceDataResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceDataHistoryRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/UpdateFirmwareRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeStudioProductRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreatePositionSpaceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateBatchProductionResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyModelDefinitionResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeletePositionFenceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetProjectListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeletePositionSpaceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceBindGatewayRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateLoRaFrequencyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/EnableTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetGatewaySubDeviceListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchStudioProductRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GenSingleDeviceSignatureOfPublicRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteDevicesRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/AppDeviceInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BindProductsResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyProjectResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BatchProductionInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeGatewayBindDevicesRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeGatewaySubProductsRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteStudioProductRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BindProductsRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyProjectRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifySpacePropertyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PublishMessageResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/BindDevicesResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeFenceBindListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/SearchKeyword.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreatePositionFenceRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeModelDefinitionRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/EnableTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DisableTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateTopicRuleResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeDeviceDataResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreateTopicRuleRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/PublishRRPCMessageResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeviceUser.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetBatchProductionsListRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeleteDeviceResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DeviceInfo.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyLoRaFrequencyResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ModifyLoRaGatewayRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/ListEventHistoryResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/GetBatchProductionsListResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeGatewayBindDevicesResponse.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/DescribeFirmwareTaskRequest.h
    ${iotexplorer_base}/include/tencentcloud/iotexplorer/v20190423/model/CreatePositionSpaceRequest.h
)

set(iotexplorer_src
    ${iotexplorer_base}/src/v20190423/IotexplorerClient.cpp
    ${iotexplorer_base}/src/v20190423/model/UpdateDevicesEnableStateResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteProjectRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DevicesItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteFenceBindRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeModelDefinitionResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/UnbindDevicesRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteDevicesResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyStudioProductResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetGatewaySubDeviceListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteStudioProductResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/BindDevicesRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeGatewaySubProductsResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetDeviceListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/TopicRulePayload.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteLoRaFrequencyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeTopicPolicyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/BindProductInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyPositionFenceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/PositionFenceItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/PositionItem.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyModelDefinitionRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateStudioProductResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CallDeviceActionSyncRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ProductDevicesPositionItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDevicePositionListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetDeviceLocationHistoryResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/UpdateFirmwareResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyPositionFenceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyStudioProductRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyPositionSpaceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateStudioProductRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ProductModelDefinition.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyFenceBindResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateBatchProductionRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeletePositionFenceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/FenceAlarmPoint.cpp
    ${iotexplorer_base}/src/v20190423/model/UploadFirmwareRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ListEventHistoryRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceDataRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/FenceBindProductItem.cpp
    ${iotexplorer_base}/src/v20190423/model/PublishRRPCMessageRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DevicePositionItem.cpp
    ${iotexplorer_base}/src/v20190423/model/ListTopicPolicyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchPositionSpaceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribePositionFenceListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GenSingleDeviceSignatureOfPublicResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDevicePositionListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetProjectListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateProjectRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeProjectResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/UnbindProductsRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchStudioProductResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeviceData.cpp
    ${iotexplorer_base}/src/v20190423/model/GetTopicRuleListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/FenceBindDeviceItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DeviceDataHistoryItem.cpp
    ${iotexplorer_base}/src/v20190423/model/GetFamilyDeviceUserListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/BindDeviceInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/ProjectEntryEx.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeBatchProductionResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ListTopicPolicyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeLoRaFrequencyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteDeviceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteLoRaFrequencyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ControlDeviceDataRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ListFirmwaresResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ReleaseStudioProductResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeSpaceFenceEventListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/PositionFenceInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteLoRaGatewayRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/UnbindProductsResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeTopicPolicyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchPositionSpaceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/LoRaFrequencyEntry.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyTopicPolicyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetPositionSpaceListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeFenceEventListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/UpdateDevicesEnableStateRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetDeviceLocationHistoryRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CallDeviceActionSyncResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateLoRaGatewayRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ReleaseStudioProductRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateProjectResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceDataHistoryResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteProjectResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateTopicPolicyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateDeviceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateDeviceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeletePositionSpaceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetStudioProductListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeFirmwareTaskResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/FirmwareInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/DisableTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/TopicRuleInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/GetCOSURLRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeStudioProductResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateFenceBindRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ListFirmwaresRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetStudioProductListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/PublishMessageRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/FamilySubDevice.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetDeviceListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifySpacePropertyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetPositionSpaceListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetCOSURLResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyFenceBindRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetTopicRuleListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeFenceEventListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyPositionSpaceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetLoRaGatewayListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ProjectEntry.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyLoRaGatewayResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/EventHistoryItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DirectBindDeviceInFamilyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/TopicRule.cpp
    ${iotexplorer_base}/src/v20190423/model/CallDeviceActionAsyncRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CallDeviceActionAsyncResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteFenceBindResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteTopicPolicyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateFenceBindResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreatePositionFenceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/TopicItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeFenceBindListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeBindedProductsResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeviceSignatureInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/PositionSpaceInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/LoRaGatewayLocation.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribePositionFenceListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeBatchProductionRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateTopicPolicyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DirectBindDeviceInFamilyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetFamilyDeviceUserListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeBindedProductsRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeLoRaFrequencyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ProductEntry.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeGatewaySubDeviceListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeSpaceFenceEventListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetLoRaGatewayListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/FenceEventItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeProjectRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/UnbindDevicesResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyLoRaFrequencyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/UploadFirmwareResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyTopicPolicyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateLoRaGatewayResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteTopicPolicyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteLoRaGatewayResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateLoRaFrequencyRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/LoRaGatewayItem.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceBindGatewayResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeGatewaySubDeviceListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ControlDeviceDataResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceDataHistoryRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/UpdateFirmwareRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeStudioProductRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreatePositionSpaceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateBatchProductionResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyModelDefinitionResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeletePositionFenceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GetProjectListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeletePositionSpaceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceBindGatewayRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateLoRaFrequencyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/EnableTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetGatewaySubDeviceListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchStudioProductRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/GenSingleDeviceSignatureOfPublicRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteDevicesRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/AppDeviceInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/BindProductsResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyProjectResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/BatchProductionInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeGatewayBindDevicesRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeGatewaySubProductsRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteStudioProductRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/BindProductsRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyProjectRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifySpacePropertyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/PublishMessageResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/BindDevicesResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeFenceBindListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/SearchKeyword.cpp
    ${iotexplorer_base}/src/v20190423/model/CreatePositionFenceRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeModelDefinitionRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/EnableTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DisableTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateTopicRuleResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeDeviceDataResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/CreateTopicRuleRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/PublishRRPCMessageResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeviceUser.cpp
    ${iotexplorer_base}/src/v20190423/model/GetBatchProductionsListRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/DeleteDeviceResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DeviceInfo.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyLoRaFrequencyResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/ModifyLoRaGatewayRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/ListEventHistoryResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/GetBatchProductionsListResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeGatewayBindDevicesResponse.cpp
    ${iotexplorer_base}/src/v20190423/model/DescribeFirmwareTaskRequest.cpp
    ${iotexplorer_base}/src/v20190423/model/CreatePositionSpaceRequest.cpp
)

add_library(tencentiotexplorer STATIC
  ${iotexplorer_public_header}
  ${iotexplorer_public_header_model}
  ${iotexplorer_src})

target_include_directories(tencentiotexplorer
    PUBLIC ${iotexplorer_base}/include
    ${CMAKE_SOURCE_DIR}/${core_base}/include
)

target_link_libraries(tencentiotexplorer
    tencentcore)